services:
  - type: web
    name: CEMA
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m pytest test_app.py  # <-- This runs your tests!
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///healthsystem.db
